build-package:
  stage: deploy
  image: python:3.10
  before_script:
    - python3 -m pip install --upgrade twine
    - python3 -m pip install --upgrade build
    - sed -i -e "s/v-latest/$CI_COMMIT_TAG/" setup.cfg
    - cat setup.cfg
  variables:
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  script:
    - python3 -m build
    - python3 -m twine upload dist/*
  only:
    - tags
