#!/bin/bash

# Author: Sam Green, Created: 04-09-19
# Bash script to loop through all the data files and pass into a python script to create plots of all the variabes.
# This code has been mainly created to 'fix' the python memory leak problem.

# Comments:
# -2019/09/04 SG: Works in serial pretty well.


printf "\n############################# PION_Python ###############################"
printf "\nThis bash script runs the pion_python code to save fig of the data.\n"
printf "\nPython2.7 is used, please make sure all python modules are installed for this version of python (does not work in Python3.+, yet)\n"
printf "#########################################################################\n"

if [ -z "$1" ];
then
	echo "***There are no input arguments***"
	echo "***How to use:   bash list-files file_location image_destination***"
	exit 1
fi

for FILE1 in "$@"
do
	if [ ! -d "$FILE1" ];
	then
		echo $FILE1 ": This is not a directory!"
	#else
		#echo $FILE1
	fi
	
	if [ -z "$2" ];
	then
		echo "***There is not enough input arguments***"
		echo "***How to use:   bash list-files file_location image_destination***"
		exit 1
	fi
done

DEST=$1
IMAG=$2

LEVELZ=$DEST*level00*

COUNTER=0

read -p "If you wish to continue, press enter..." < /dev/tty

printf "\nDo you wish to run this script in Serial or Parallel? (type s or p)\n"
read -p '....: ' str1

if [[ "$str1" == "s" ]];
#if [ "$str1" == "s" ] && [ "$str1" == "serial"];
then
	echo '....Running python script in serial....'
	for file in $LEVELZ
	do
		
		python Library/plot_nestedgrid_3dslice.py $IMAG $DEST*${file:${#file}-13}
		COUNTER=$[COUNTER + 1]
		echo $COUNTER "of" "${#LEVELZ[@]}" "files analysed and saved"
	
	done

elif [[ "$str1" == "p" ]];
then
	echo '....Running python script in parallel....'
	echo 'This actually does not work yet... but it will soon!'
	#parallel 'python bash_plot.py $IMAG {1} {1} {1} ${#{1}}' ::: $LEVELZ

else
	echo 'Please type s or p'
fi


